require "local.lvim.lsp"
require "local.lvim.null-ls"
require "local.lvim.cmp"
require "local.lvim.lazy"
require "local.lvim.alpha"
require "local.lvim.bufferline"
require "local.lvim.indentlines"
require "local.lvim.lualine"
require "local.lvim.luasnip"
require "local.lvim.nvimtree"
require "local.lvim.project"
require "local.lvim.telescope"
require "local.lvim.terminal"
require "local.lvim.treesitter"
require "local.lvim.which_key"

require "local.lvim.option"
